M48
; DRILL file {KiCad 7.0.2-0} date 2023 May 31, Wednesday 17:16:28
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-05-31T17:16:28-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2-0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0941
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1358
%
G90
G05
T1
X5.1969Y-1.7323
X5.1969Y-5.748
X6.1417Y-1.7323
X6.1417Y-5.748
T2
X5.2441Y-1.9949
T3
X5.2441Y-4.4961
X5.874Y-2.3228
T0
M30
